const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lumen', {
  platform: process.platform,
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (partial) => ipcRenderer.invoke('set-settings', partial),
  lumenSearch: (query) => ipcRenderer.invoke('lumen-search', query),
  lumenSearchStats: () => ipcRenderer.invoke('lumen-search-stats'),
  toggleLumenSearch: (enabled) => ipcRenderer.invoke('toggle-lumen-search', enabled),
  pickWallpaper: () => ipcRenderer.invoke('pick-wallpaper'),
  aiChat: (payload) => ipcRenderer.invoke('ai-chat', payload),
  pickLocalModel: () => ipcRenderer.invoke('pick-local-model'),
  loadLocalModel: (opts) => ipcRenderer.invoke('load-local-model', opts || {}),
  unloadLocalModel: () => ipcRenderer.invoke('unload-local-model'),
  localAiStatus: () => ipcRenderer.invoke('local-ai-status'),
  onLocalAiStatus: (cb) => { ipcRenderer.on('local-ai-status', (_e, data) => cb(data)); },
  resolvePath: (p) => ipcRenderer.invoke('resolve-path', p),
  getGuestPreloadPath: () => ipcRenderer.invoke('get-guest-preload-path'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  onOpenUrlNewTab: (cb) => { ipcRenderer.on('open-url-new-tab', (_e, url) => cb(url)); },
  onDownloadProgress: (cb) => { ipcRenderer.on('download-progress', (_e, data) => cb(data)); },
  onNavigationBlocked: (cb) => { ipcRenderer.on('navigation-blocked', (_e, url) => cb(url)); },
  saveTabs: (tabs) => ipcRenderer.invoke('save-tabs', tabs),
  loadTabs: () => ipcRenderer.invoke('load-tabs'),
  addHistory: (entry) => ipcRenderer.invoke('add-history', entry),
  getHistory: () => ipcRenderer.invoke('get-history'),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  getPasswords: () => ipcRenderer.invoke('get-passwords'),
  savePassword: (entry) => ipcRenderer.invoke('save-password', entry),
  deletePassword: (url, username) => ipcRenderer.invoke('delete-password', url, username),
  checkAdult: (url) => ipcRenderer.invoke('check-adult', url),
  getWelcomePath: () => ipcRenderer.invoke('get-welcome-path'),
  addBookmark: (entry) => ipcRenderer.invoke('add-bookmark', entry),
  removeBookmark: (url) => ipcRenderer.invoke('remove-bookmark', url),
  getBookmarks: () => ipcRenderer.invoke('get-bookmarks'),
  checkBookmark: (url) => ipcRenderer.invoke('check-bookmark', url),
  loadExtension: (extPath) => ipcRenderer.invoke('load-extension', extPath),
  removeExtension: (id) => ipcRenderer.invoke('remove-extension', id),
  getExtensions: () => ipcRenderer.invoke('get-extensions'),
  pickExtensionDir: () => ipcRenderer.invoke('pick-extension-dir'),
  getDownloads: () => ipcRenderer.invoke('get-downloads'),
  clearDownloads: () => ipcRenderer.invoke('clear-downloads'),
  clearBrowsingData: (opts) => ipcRenderer.invoke('clear-browsing-data', opts),
  setProxy: (config) => ipcRenderer.invoke('set-proxy', config),
  getProxy: () => ipcRenderer.invoke('get-proxy'),
  importBookmarks: () => ipcRenderer.invoke('import-bookmarks'),
  exportBookmarks: () => ipcRenderer.invoke('export-bookmarks'),
  addBrowserHistory: (entry) => ipcRenderer.invoke('add-browser-history', entry),
  getBrowserHistory: () => ipcRenderer.invoke('get-browser-history'),
  clearBrowserHistory: () => ipcRenderer.invoke('clear-browser-history'),
  downloadFile: (url) => ipcRenderer.invoke('download-file', url),
});
